project:
  type: website

website:
  title: "Reproducible Research · Course Blog"
  description: "One week of reproducible bioinformatics"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - icon: github
        # replace with the address of YOUR repository
        href: https://github.com/zanabrilej22/New_blog.git 
  page-footer:
    center: "Zana Brilej · Reproducible Research in Bioinformatics, September 2026"

format:
  html:
    theme:
      light: minty
      dark: minty
    css: styles.css
    toc: true
    toc-title: "On this page"
    code-copy: true
    code-overflow: wrap
    highlight-style: github


execute:
  freeze: auto
